package com.todolab.task.repository;

import com.todolab.config.QuerydslConfig;
import com.todolab.dday.domain.DdayGoal;
import com.todolab.support.RepositoryTestSupport;
import com.todolab.task.domain.Task;
import com.todolab.task.domain.TaskStatus;
import com.todolab.task.domain.TaskType;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.BDDAssertions.then;

@DataJpaTest
@Import(QuerydslConfig.class)
@ActiveProfiles("test")
class TaskRepositoryTest extends RepositoryTestSupport {

    @Autowired
    TaskRepository taskRepository;

    @Test
    @DisplayName("일정(Task) 저장 성공")
    void save_success() {
        // given
        LocalDateTime startAt = LocalDateTime.of(2025, 11, 27, 10, 30);
        LocalDateTime endAt = LocalDateTime.of(2025, 11, 27, 11, 30);

        Task task = Task.builder()
                .title("hello")
                .description("desc")
                .startAt(startAt)
                .endAt(endAt)
                .allDay(false)
                .category("일")
                .build();

        // when
        Task saved = taskRepository.save(task);
        flushAndClear();

        // then
        then(saved.getId()).isNotNull();
        then(saved.getTitle()).isEqualTo("hello");
        then(saved.getDescription()).isEqualTo("desc");
        then(saved.getStartAt()).isEqualTo(startAt);
        then(saved.getEndAt()).isEqualTo(endAt);
        then(saved.isAllDay()).isFalse();
        then(saved.getCategory()).isEqualTo("일");
        then(saved.getStatus()).isEqualTo(TaskStatus.TODAY);
        then(saved.getTargetDate()).isEqualTo(startAt.toLocalDate());
        then(saved.getCompletedAt()).isNull();
    }

    @Test
    @DisplayName("@PrePersist 를 통해 createdAt 이 자동으로 세팅된다")
    void createdAt_autoGenerated() {
        // given
        Task task = Task.builder()
                .title("created test")
                .description("desc")
                .startAt(LocalDateTime.of(2025, 11, 30, 9, 0))
                .endAt(null)
                .allDay(false)
                .category("공부")
                .build();

        // when
        Task saved = taskRepository.save(task);
        flushAndClear();

        // then
        then(saved.getCreatedAt()).isNotNull();
        then(saved.getCreatedAt()).isBeforeOrEqualTo(LocalDateTime.now());
    }

    @Test
    @DisplayName("findByDateRange()는 조회 범위 [start,end) 와 겹치는 기간 일정도 포함한다")
    void findByDateRange_includes_long_period_task_on_partial_range() {
        // given
        // 조회 범위: 11/02 ~ 11/07(포함) => endExclusive = 11/08 00:00
        LocalDateTime startInclusive = LocalDateTime.of(2025, 11, 2, 0, 0);
        LocalDateTime endExclusive = LocalDateTime.of(2025, 11, 8, 0, 0);

        // A: 11월 전체(11/01~11/30) 기간 일정
        Task a = Task.builder()
                .title("A-11월전체")
                .description("11월 1일부터 30일까지")
                .startAt(LocalDateTime.of(2025, 11, 1, 0, 0))
                .endAt(LocalDateTime.of(2025, 12, 1, 0, 0))
                .allDay(true)
                .category("일")
                .build();

        // 범위 내 단일 일정
        Task b = Task.builder()
                .title("B-단일")
                .description("11/03 단일")
                .startAt(LocalDateTime.of(2025, 11, 3, 10, 0))
                .endAt(null)
                .allDay(false)
                .category("공부")
                .build();

        // 범위 밖(겹침 없음)
        Task c = Task.builder()
                .title("C-비겹침")
                .description("10월 일정")
                .startAt(LocalDateTime.of(2025, 10, 1, 0, 0))
                .endAt(LocalDateTime.of(2025, 10, 2, 0, 0))
                .allDay(true)
                .category("기타")
                .build();

        // 미정(조회 대상 제외)
        Task unscheduled = Task.builder()
                .title("미정")
                .description("미정")
                .startAt(null)
                .endAt(null)
                .allDay(false)
                .category("기타")
                .build();

        taskRepository.saveAll(List.of(a, b, c, unscheduled));
        flushAndClear();

        // when
        List<Task> results = taskRepository.findByDateRange(startInclusive, endExclusive);

        // then
        then(results).extracting("title")
                .contains("A-11월전체", "B-단일");

        then(results).extracting("title")
                .doesNotContain("C-비겹침", "미정");
    }

    @Test
    @DisplayName("findByDateRange()는 전날 시작해 조회 시작일에 걸치는 기간 일정도 포함한다")
    void findByDateRange_includes_crossing_period_task_on_day_range() {
        // given
        // 11/01 하루 조회: [11/01 00:00, 11/02 00:00)
        LocalDateTime startInclusive = LocalDateTime.of(2025, 11, 1, 0, 0);
        LocalDateTime endExclusive = LocalDateTime.of(2025, 11, 2, 0, 0);

        Task crossing = Task.builder()
                .title("crossing")
                .description("10/31~11/01 걸침")
                .startAt(LocalDateTime.of(2025, 10, 31, 9, 0))
                .endAt(LocalDateTime.of(2025, 11, 1, 9, 30))
                .allDay(false)
                .category("기타")
                .build();

        Task boundaryExcluded = Task.builder()
                .title("boundaryExcluded")
                .description("startAt == endExclusive")
                .startAt(LocalDateTime.of(2025, 11, 2, 0, 0))
                .endAt(null)
                .allDay(false)
                .category("기타")
                .build();

        taskRepository.saveAll(List.of(crossing, boundaryExcluded));
        flushAndClear();

        // when
        List<Task> results = taskRepository.findByDateRange(startInclusive, endExclusive);

        // then
        then(results).extracting("title")
                .contains("crossing");

        then(results).extracting("title")
                .doesNotContain("boundaryExcluded");
    }

    @Test
    @DisplayName("findByDateRange()는 조회 범위와 겹치지 않는 기간 일정은 제외한다")
    void findByDateRange_excludes_non_overlapping_period_task() {
        // given
        LocalDateTime startInclusive = LocalDateTime.of(2025, 11, 2, 0, 0);
        LocalDateTime endExclusive = LocalDateTime.of(2025, 11, 8, 0, 0);

        Task nonOverlap = Task.builder()
                .title("nonOverlap")
                .description("겹치지 않음")
                .startAt(LocalDateTime.of(2025, 10, 20, 0, 0))
                .endAt(LocalDateTime.of(2025, 10, 21, 0, 0))
                .allDay(true)
                .category("기타")
                .build();

        taskRepository.save(nonOverlap);
        flushAndClear();

        // when
        List<Task> results = taskRepository.findByDateRange(startInclusive, endExclusive);

        // then
        then(results).extracting("title")
                .doesNotContain("nonOverlap");
    }

    @Test
    @DisplayName("findByDateRangeAndType()은 지정한 TaskType만 조회한다")
    void findByDateRangeAndType_filters_taskType() {
        // given
        LocalDateTime startInclusive = LocalDateTime.of(2026, 5, 17, 0, 0);
        LocalDateTime endExclusive = LocalDateTime.of(2026, 5, 18, 0, 0);

        Task schedule = Task.builder()
                .title("schedule")
                .type(TaskType.SCHEDULE)
                .startAt(LocalDateTime.of(2026, 5, 17, 10, 0))
                .endAt(null)
                .allDay(false)
                .category("일")
                .build();

        Task todo = Task.builder()
                .title("todo")
                .type(TaskType.TODO)
                .startAt(LocalDateTime.of(2026, 5, 17, 11, 0))
                .endAt(null)
                .allDay(false)
                .category("할일")
                .build();

        taskRepository.saveAll(List.of(schedule, todo));
        flushAndClear();

        // when
        List<Task> results = taskRepository.findByDateRangeAndType(startInclusive, endExclusive, TaskType.SCHEDULE);

        // then
        then(results).extracting("title")
                .containsExactly("schedule");
    }

    @Test
    @DisplayName("findUnscheduledTask()는 startAt/endAt 둘 다 null인 Task만 조회한다")
    void findUnscheduledTask_only_null_start_end() {
        // given
        Task unscheduled1 = Task.builder()
                .title("u1")
                .description("d1")
                .startAt(null)
                .endAt(null)
                .allDay(false)
                .category("일")
                .build();

        Task scheduled1 = Task.builder()
                .title("s1")
                .description("d2")
                .startAt(LocalDateTime.of(2026, 1, 1, 10, 0))
                .endAt(null)
                .allDay(false)
                .category("일")
                .build();

        Task scheduled2 = Task.builder()
                .title("s2")
                .description("d3")
                .startAt(LocalDateTime.of(2026, 1, 2, 10, 0))
                .endAt(LocalDateTime.of(2026, 1, 2, 11, 0))
                .allDay(false)
                .category("일")
                .build();

        taskRepository.saveAll(List.of(unscheduled1, scheduled1, scheduled2));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findUnscheduledTask();

        // then
        then(result).hasSize(1);
        then(result.getFirst().getTitle()).isEqualTo("u1");
        then(result.getFirst().getStartAt()).isNull();
        then(result.getFirst().getEndAt()).isNull();
    }

    @Test
    @DisplayName("findByStatus()는 지정한 상태의 Task만 조회한다")
    void findByStatus_filters_status() {
        // given
        Task inbox = Task.builder()
                .title("inbox")
                .status(TaskStatus.INBOX)
                .build();

        Task today = Task.builder()
                .title("today")
                .status(TaskStatus.TODAY)
                .targetDate(LocalDate.of(2026, 5, 20))
                .build();

        taskRepository.saveAll(List.of(inbox, today));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findByStatus(TaskStatus.INBOX);

        // then
        then(result).extracting("title")
                .containsExactly("inbox");
    }

    @Test
    @DisplayName("findPlannedTasks()는 반개방 계획 날짜 범위의 Today Task만 조회한다")
    void findPlannedTasks_filtersHalfOpenDateRange() {
        // given
        LocalDate targetDate = LocalDate.of(2026, 5, 20);

        Task today = Task.builder()
                .title("today")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .build();

        Task otherDay = Task.builder()
                .title("otherDay")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate.plusDays(1))
                .build();

        Task inbox = Task.builder()
                .title("inbox")
                .status(TaskStatus.INBOX)
                .build();

        taskRepository.saveAll(List.of(today, otherDay, inbox));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findPlannedTasks(targetDate, targetDate.plusDays(1));

        // then
        then(result).extracting("title")
                .containsExactly("today");
    }

    @Test
    @DisplayName("findPlannedTasks()는 같은 날짜에서 시간 일정 우선, 종일 할 일은 실행 순서순으로 조회한다")
    void findPlannedTasks_ordersTodayTasksByTimeAndTodayOrder() {
        // given
        LocalDate targetDate = LocalDate.of(2026, 5, 20);

        Task allDaySecond = Task.builder()
                .title("allDaySecond")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .startAt(targetDate.atStartOfDay())
                .endAt(targetDate.plusDays(1).atStartOfDay())
                .allDay(true)
                .todayOrder(2)
                .build();
        Task timed = Task.builder()
                .title("timed")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .startAt(targetDate.atTime(14, 0))
                .endAt(targetDate.atTime(15, 0))
                .todayOrder(3)
                .build();
        Task allDayFirst = Task.builder()
                .title("allDayFirst")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .startAt(targetDate.atStartOfDay())
                .endAt(targetDate.plusDays(1).atStartOfDay())
                .allDay(true)
                .todayOrder(1)
                .build();

        taskRepository.saveAll(List.of(allDaySecond, timed, allDayFirst));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findPlannedTasks(targetDate, targetDate.plusDays(1));

        // then
        then(result).extracting("title")
                .containsExactly("timed", "allDayFirst", "allDaySecond");
    }

    @Test
    @DisplayName("findMaxTodayOrder()는 지정 날짜의 가장 큰 실행 순서를 반환한다")
    void findMaxTodayOrder_success() {
        // given
        LocalDate targetDate = LocalDate.of(2026, 5, 20);
        Task first = Task.builder()
                .title("first")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .todayOrder(1)
                .build();
        Task last = Task.builder()
                .title("last")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate)
                .todayOrder(4)
                .build();
        Task otherDate = Task.builder()
                .title("otherDate")
                .status(TaskStatus.TODAY)
                .targetDate(targetDate.plusDays(1))
                .todayOrder(9)
                .build();

        taskRepository.saveAll(List.of(first, last, otherDate));
        flushAndClear();

        // when
        Integer result = taskRepository.findMaxTodayOrder(targetDate);

        // then
        then(result).isEqualTo(4);
    }

    @Test
    @DisplayName("findPlannedTasks()는 하한 없이 기준일 이전의 Today Task를 오래된 계획일순으로 조회한다")
    void findPlannedTasks_filtersBeforeDateWithoutLowerBound() {
        // given
        LocalDate referenceDate = LocalDate.of(2026, 5, 20);

        Task oldest = Task.builder()
                .title("oldest")
                .status(TaskStatus.TODAY)
                .targetDate(referenceDate.minusDays(3))
                .build();

        Task yesterday = Task.builder()
                .title("yesterday")
                .status(TaskStatus.TODAY)
                .targetDate(referenceDate.minusDays(1))
                .build();

        Task today = Task.builder()
                .title("today")
                .status(TaskStatus.TODAY)
                .targetDate(referenceDate)
                .build();

        Task future = Task.builder()
                .title("future")
                .status(TaskStatus.TODAY)
                .targetDate(referenceDate.plusDays(1))
                .build();

        Task done = Task.builder()
                .title("done")
                .status(TaskStatus.DONE)
                .targetDate(referenceDate.minusDays(2))
                .completedAt(referenceDate.minusDays(2).atTime(18, 0))
                .build();

        Task inbox = Task.builder()
                .title("inbox")
                .status(TaskStatus.INBOX)
                .build();

        taskRepository.saveAll(List.of(yesterday, today, done, oldest, future, inbox));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findPlannedTasks(null, referenceDate);

        // then
        then(result).extracting("title")
                .containsExactly("oldest", "yesterday");
    }

    @Test
    @DisplayName("findDoneTasks()는 지정한 날짜에 완료한 Done Task만 완료 시간 최신순으로 조회한다")
    void findDoneTasks_filters_completedDate() {
        // given
        LocalDate completedDate = LocalDate.of(2026, 5, 20);

        Task morning = Task.builder()
                .title("morning")
                .status(TaskStatus.DONE)
                .completedAt(completedDate.atTime(9, 0))
                .build();

        Task evening = Task.builder()
                .title("evening")
                .status(TaskStatus.DONE)
                .completedAt(completedDate.atTime(21, 0))
                .build();

        Task otherDay = Task.builder()
                .title("otherDay")
                .status(TaskStatus.DONE)
                .completedAt(completedDate.plusDays(1).atStartOfDay())
                .build();

        Task today = Task.builder()
                .title("today")
                .status(TaskStatus.TODAY)
                .targetDate(completedDate)
                .build();

        taskRepository.saveAll(List.of(morning, evening, otherDay, today));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findDoneTasks(completedDate);

        // then
        then(result).extracting("title")
                .containsExactly("evening", "morning");
    }

    @Test
    @DisplayName("findByDdayGoalId()는 D-Day 목표에 연결된 Task만 실행 날짜순으로 조회한다")
    void findByDdayGoalId_filters_goal() {
        // given
        DdayGoal goal = new DdayGoal("정보처리기사", LocalDate.of(2026, 6, 10));
        DdayGoal otherGoal = new DdayGoal("포트폴리오 제출", LocalDate.of(2026, 6, 5));
        em.persist(goal);
        em.persist(otherGoal);

        Task first = Task.builder()
                .title("기출 20문제 풀기")
                .status(TaskStatus.TODAY)
                .targetDate(LocalDate.of(2026, 5, 30))
                .ddayGoal(goal)
                .build();

        Task second = Task.builder()
                .title("오답 정리")
                .status(TaskStatus.TODAY)
                .targetDate(LocalDate.of(2026, 5, 31))
                .ddayGoal(goal)
                .build();

        Task other = Task.builder()
                .title("포트폴리오 README 정리")
                .status(TaskStatus.TODAY)
                .targetDate(LocalDate.of(2026, 5, 30))
                .ddayGoal(otherGoal)
                .build();

        Task unlinked = Task.builder()
                .title("연결 없는 일")
                .status(TaskStatus.TODAY)
                .targetDate(LocalDate.of(2026, 5, 30))
                .build();

        taskRepository.saveAll(List.of(second, other, first, unlinked));
        flushAndClear();

        // when
        List<Task> result = taskRepository.findByDdayGoalId(goal.getId());

        // then
        then(result).extracting("title")
                .containsExactly("기출 20문제 풀기", "오답 정리");
    }
}
