-- APP_USER
CREATE TABLE APP_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(50) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL)
);

-- D-DAY_GOAL
CREATE TABLE DDAY_GOAL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    TARGET_DATE DATE NOT NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_DDAY_GOAL_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

-- RECURRENCE_SERIES
CREATE TABLE RECURRENCE_SERIES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NULL,
    FREQUENCY VARCHAR(30) NOT NULL,
    INTERVAL_VALUE INT NOT NULL DEFAULT 1,
    RRULE VARCHAR(500) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL,
    RECURRENCE_START_AT DATETIME NOT NULL,
    RECURRENCE_UNTIL DATE NULL,
    RECURRENCE_COUNT INT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RECURRENCE_SERIES_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

-- TASK
CREATE TABLE TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(30) NOT NULL DEFAULT 'SCHEDULE',
    START_AT DATETIME NULL,
    END_AT DATETIME NULL,
    ALL_DAY BOOLEAN NOT NULL DEFAULT FALSE,
    CATEGORY VARCHAR(255) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'INBOX',
    TARGET_DATE DATE NULL,
    COMPLETED_AT DATETIME NULL,
    CARRY_OVER_COUNT INT NOT NULL DEFAULT 0,
    DEFER_REASON VARCHAR(30) NULL,
    DDAY_GOAL_ID BIGINT NULL,
    RECURRENCE_SERIES_ID BIGINT NULL,
    OCCURRENCE_DATE DATE NULL,
    ORIGINAL_OCCURRENCE_DATE DATE NULL,
    RECURRENCE_EXCEPTION VARCHAR(30) NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_DDAY_GOAL FOREIGN KEY (DDAY_GOAL_ID) REFERENCES DDAY_GOAL(ID),
    CONSTRAINT FK_TASK_RECURRENCE_SERIES FOREIGN KEY (RECURRENCE_SERIES_ID) REFERENCES RECURRENCE_SERIES(ID),
    CONSTRAINT FK_TASK_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);
