-- APP_USER
CREATE TABLE APP_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(50) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL)
);

-- D-DAY_GOAL
CREATE TABLE DDAY_GOAL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    TARGET_DATE DATE NOT NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_DDAY_GOAL_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

-- TASK
CREATE TABLE TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(30) NOT NULL DEFAULT 'SCHEDULE',
    START_AT DATETIME NULL,
    END_AT DATETIME NULL,
    ALL_DAY BOOLEAN NOT NULL DEFAULT FALSE,
    CATEGORY VARCHAR(255) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'INBOX',
    TARGET_DATE DATE NULL,
    COMPLETED_AT DATETIME NULL,
    CARRY_OVER_COUNT INT NOT NULL DEFAULT 0,
    DEFER_REASON VARCHAR(30) NULL,
    DDAY_GOAL_ID BIGINT NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_DDAY_GOAL FOREIGN KEY (DDAY_GOAL_ID) REFERENCES DDAY_GOAL(ID),
    CONSTRAINT FK_TASK_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);
