ALTER TABLE DDAY_GOAL
    ADD COLUMN OWNER_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_DDAY_GOAL_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID);

ALTER TABLE TASK
    ADD COLUMN OWNER_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_TASK_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID);
