START TRANSACTION;

-- 실행일만 남은 Task는 해당 날짜의 자동 종일 일정으로 복구한다.
UPDATE TASK
SET START_AT = CAST(TARGET_DATE AS DATETIME),
    END_AT = DATE_ADD(CAST(TARGET_DATE AS DATETIME), INTERVAL 1 DAY),
    ALL_DAY = TRUE,
    SCHEDULE_SOURCE = 'AUTO_TODAY'
WHERE TARGET_DATE IS NOT NULL
  AND START_AT IS NULL
  AND STATUS IN ('TODAY', 'DONE');

-- 일정 날짜가 실행일과 다르면 시간과 기간을 유지한 채 날짜 전체를 이동한다.
UPDATE TASK AS T
JOIN (
    SELECT ID,
           DATEDIFF(TARGET_DATE, DATE(START_AT)) AS DAYS_TO_MOVE
    FROM TASK
    WHERE TARGET_DATE IS NOT NULL
      AND START_AT IS NOT NULL
      AND DATE(START_AT) <> TARGET_DATE
) AS MISMATCHED ON MISMATCHED.ID = T.ID
SET T.START_AT = DATE_ADD(T.START_AT, INTERVAL MISMATCHED.DAYS_TO_MOVE DAY),
    T.END_AT = CASE
        WHEN T.END_AT IS NULL THEN NULL
        ELSE DATE_ADD(T.END_AT, INTERVAL MISMATCHED.DAYS_TO_MOVE DAY)
    END;

COMMIT;
