CREATE TABLE APP_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(50) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL)
);
